server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;

    location /bus-tracker/ {
        try_files $uri $uri/ /bus-tracker/index.html;
    }

    location = / {
        return 301 /bus-tracker/;
    }
}
